name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SWI_VERSION: devel

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install swivm
      uses: fnogatz/swivm/actions/load@add-github-action
      with:
        swi-prolog-version: devel

    - name: Run tests
      run: |
        source ~/.swivm/swivm.sh
        swivm use $SWI_VERSION
        make test
